import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ToastContainer } from "react-toastify";
// import "react-toastify/dist/ReactToastify.css";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Variable } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider 
        appearance={{
          layout:{
            logoImageUrl:'assets/logo.svg',
            socialButtonsVariant:'iconButton',
            
          },
          variables: {
            colorPrimary: "blue",
            colorText:'#fff',
            colorBackground:"#1C1F2E",
            colorInputBackground:"#252a41",
            colorInputText:'#fff',
            
          },
        }}
      >
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-dark-1`}>
          {children}
        </body>
      </ClerkProvider>
    </html>
  );
}
